#!/usr/bin/env python3
"""
Plot SLAG simulation data from CSV files with embedded metadata.

This script reads CSV files generated by Example_SLAG_save_data.m
and creates plots of diffraction efficiency vs photon energy.

Usage:
    python plot_simulation_data.py simulation_csv_file [experimental_csv_file] [reflec_txt_file] [reflec_angle_deg]

The simulation CSV file is required (generated by Example_SLAG_save_data.m).
The experimental CSV file is optional and will be overlaid on the simulation
plot if provided. Experimental files should have semicolon separators with
comma decimal separators (e.g., HORIBA/ELISA format).
The reflec text file is optional and can be overlaid using either the 2 deg or
4 deg column; change the angle selector in this script or pass it on the CLI.
"""

import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend for saving files
import numpy as np
import sys
import os
import glob
import re
from datetime import datetime


def parse_csv_with_metadata(filename):
    """
    Parse CSV file with metadata comments (lines starting with #).
    
    Returns:
        metadata: dict containing all metadata fields
        energy: numpy array of photon energies (eV)
        efficiency: numpy array of diffraction efficiencies
    """
    metadata = {}
    energy = []
    efficiency = []
    
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            
            # Skip empty lines
            if not line:
                continue
            
            # Parse metadata (lines starting with #)
            if line.startswith('#'):
                # Extract key-value pairs
                if ':' in line:
                    key_value = line[1:].strip()  # Remove #
                    if ':' in key_value:
                        key, value = key_value.split(':', 1)
                        key = key.strip()
                        value = value.strip()
                        
                        # Try to convert to appropriate type
                        try:
                            if '.' in value:
                                metadata[key] = float(value)
                            else:
                                metadata[key] = int(value)
                        except ValueError:
                            metadata[key] = value
                continue
            
            # Parse data lines (semicolon-separated)
            if ';' in line:
                parts = line.split(';')
                if len(parts) >= 2:
                    try:
                        e = float(parts[0])
                        eff = float(parts[1])
                        energy.append(e)
                        efficiency.append(eff)
                    except ValueError:
                        continue
    
    return metadata, np.array(energy), np.array(efficiency)


def print_metadata(metadata):
    """Print metadata in a formatted way."""
    
    print("SIMULATION METADATA: ")
    
    
    sections = [
        ('GRATING PARAMETERS', ['grating_period_lpermm', 'diffraction_order', 
                                'grating_width_to_period_ratio', 'grating_depth_nm',
                                'trapezoid_angle_left_deg', 'trapezoid_angle_right_deg',
                                'substrate_material']),
        ('LAYER PARAMETERS', ['layer_material', 'layer_thickness_nm']),
        ('SIMULATION PARAMETERS', ['z_resolution_nm', 'x_resolution_nm', 'fourier_orders']),
        ('INCIDENCE CONDITIONS', ['grazing_angle_deg', 'photon_energy_min_eV', 
                                  'photon_energy_max_eV', 'photon_energy_step_eV',
                                  'polarization']),
    ]
    
    for section_name, keys in sections:
        print(f"\n{section_name}:")
        
        for key in keys:
            if key in metadata:
                print(f"  {key}: {metadata[key]}")
    


def plot_data(metadata, energy, efficiency,
              experimental_energy=None, experimental_efficiency=None,
              reflec_diff_energy = None, reflec_diff_efficiency= None,
              reflec_specs_energy= None, reflec_specs_efficiency= None,
              reflec_cont_energy= None, reflec_cont_efficiency= None,
              reflec_afm_energy= None, reflec_afm_efficiency= None,
              reflec_grazing_angle_deg=None,
              show_plot=True, save_format='png'):
    """
    Create and save plot of simulation data with optional overlays.
    
    Args:
        metadata: dict with simulation metadata
        energy: array of photon energies (eV)
        efficiency: array of diffraction efficiencies
        experimental_energy: array of experimental photon energies (eV)
        experimental_efficiency: array of experimental efficiencies
        reflec_energy: array of reflec photon energies (eV)
        reflec_efficiency: array of selected reflec efficiencies
        reflec_grazing_angle_deg: selected grazing angle for label text
        show_plot: whether to display plot interactively
        save_format: image format to save ('png', 'pdf', 'svg')
    """
    # Create figure with single subplot
    fig, ax = plt.subplots(1, 1, figsize=(10, 7))
    
    # Main plot: Efficiency vs Energy (Simulation data)
    ax.plot(energy, efficiency, 'b-o', linewidth=.3, markersize=.5, label='Reticolo')
    
    # Overlay experimental data if provided
    if experimental_energy is not None and experimental_efficiency is not None:
        ax.plot(experimental_energy, experimental_efficiency, 'r-o', linewidth=.3, 
                markersize=.5, label='Experimental', alpha=0.8)

    # Overlay reflec data if provided
    if reflec_diff_energy is not None and reflec_diff_efficiency is not None:
        if reflec_grazing_angle_deg is not None:
            reflec_label = f"REFLEC_DIFFMOD {reflec_grazing_angle_deg} deg"
        else:
            reflec_label = "reflec"
        ax.plot(reflec_diff_energy, reflec_diff_efficiency, 'g-o', linewidth=.5,
                markersize=1, label=reflec_label, alpha=0.8)
    
 
    # Overlay reflec data if provided
    if reflec_specs_energy is not None and reflec_specs_efficiency is not None:
        if reflec_grazing_angle_deg is not None:
            reflec_specs_label = f"reflec {reflec_grazing_angle_deg} deg"
        else:
            reflec_specs_label = "reflec"
        ax.plot(reflec_specs_energy, reflec_specs_efficiency, 'c-o', linewidth=1,
                markersize=1.5, label='REFLEC_specs', alpha=0.8)

 
    # Overlay reflec data if provided
    if reflec_cont_energy is not None and reflec_cont_efficiency is not None:
        if reflec_grazing_angle_deg is not None:
            reflec_cont_label = f"reflec {reflec_grazing_angle_deg} deg"
        else:
            reflec_cont_label = "reflec"
        ax.plot(reflec_cont_energy, reflec_cont_efficiency, 'k-o', linewidth=.5,
                markersize=1., label='REFLEC_cont', alpha=0.8)
    
 
    # Overlay reflec data if provided
    if reflec_afm_energy is not None and reflec_afm_efficiency is not None:
        if reflec_grazing_angle_deg is not None:
            reflec_afm_label = f"reflec {reflec_grazing_angle_deg} deg"
        else:
            reflec_afm_label = "reflec"
        ax.plot(reflec_afm_energy, reflec_afm_efficiency, 'm-o', linewidth=.5,
                markersize=1, label='REFLEC_afm', alpha=0.8)
    
    ax.set_xlabel('Photon Energy (eV)', fontsize=12)
    ax.set_ylabel('Diffraction Efficiency', fontsize=12)
             
    # Create title from metadata
    title_parts = []
    if 'grating_period_lpermm' in metadata:
        title_parts.append(f"{metadata['grating_period_lpermm']} l/mm")
    if 'grazing_angle_deg' in metadata:
        title_parts.append(f"α = {metadata['grazing_angle_deg']:.1f}°")
    if 'diffraction_order' in metadata:
        title_parts.append(f"Order {metadata['diffraction_order']}")
    
    title = 'SLAG Simulation: ' + ', '.join(title_parts)
    ax.set_title(title, fontsize=14, fontweight='bold')
    ax.grid(True, alpha=0.3)
    ax.legend(loc='best')
    
    # Determine y-axis limits
    all_efficiency = list(efficiency)
    if experimental_efficiency is not None:
        all_efficiency.extend(experimental_efficiency)
    if reflec_diff_efficiency is not None:
        all_efficiency.extend(reflec_diff_efficiency)
    all_energy = list(energy)
    if experimental_energy is not None:
        all_energy.extend(experimental_energy)
    if reflec_diff_energy is not None:
        all_energy.extend(reflec_diff_energy)

    ax.set_ylim([0, max(all_efficiency) * 1.1])
    ax.set_xlim([min(all_energy), max(all_energy)])

    
    plt.tight_layout()
    
    # Generate output filename
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    output_filename = f"SLAG_plot_{timestamp}.{save_format}"
    
    # Save figure
    plt.savefig(output_filename, dpi=150, bbox_inches='tight')
    print(f"\nPlot saved to: {output_filename}")
    
    if show_plot:
        plt.show()
    
    plt.close()
    
    return output_filename


def parse_experimental_csv(filename):
    """
    Parse experimental CSV file with different format.
    
    Experimental files have:
    - 3 header lines to skip
    - Semicolon separator
    - Comma as decimal separator
    
    Returns:
        energy: numpy array of photon energies (eV)
        efficiency: numpy array of diffraction efficiencies
    """
    energy = []
    efficiency = []
    
    with open(filename, 'r') as f:
        # Skip first 3 header lines
        for _ in range(3):
            f.readline()
        
        # Read data lines
        for line in f:
            line = line.strip()
            if not line:
                continue
            
            # Parse semicolon-separated values
            parts = line.split(';')
            if len(parts) >= 2:
                try:
                    # Replace comma with dot for decimal separator
                    e = float(parts[0].replace(',', '.'))
                    eff = float(parts[1].replace(',', '.'))
                    energy.append(e)
                    efficiency.append(eff)
                except ValueError:
                    continue
    
    return np.array(energy), np.array(efficiency)


def parse_reflec_simulations(filename, grazing_angle_deg=4):
    """
    Parse reflec reflection table and select one grazing-angle column.

    The file is tab/whitespace separated and the first data column is energy.
    The next columns contain simulation results for different grazing angles.

    Args:
        filename: path to the text file
        grazing_angle_deg: 2 or 4, selects the matching result column

    Returns:
        energy: numpy array of photon energies
        efficiency: numpy array of selected simulation efficiencies
    """
    angle_to_column = {2: 2, 4: 3}
    if grazing_angle_deg not in angle_to_column:
        raise ValueError(
            f"Unsupported reflec grazing angle {grazing_angle_deg}. "
            "Use 2 or 4."
        )

    rows = []
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            # Header lines contain text; only keep fully numeric rows.
            parts = re.split(r'\s+', line)
            try:
                row = [float(part.replace(',', '.')) for part in parts]
            except ValueError:
                continue

            if len(row) >= 3:
                rows.append(row)

    if not rows:
        raise ValueError(f"No numeric data found in reflec file: {filename}")

    data = np.array(rows, dtype=float)
    col = angle_to_column[grazing_angle_deg]
    if data.shape[1] <= col:
        raise ValueError(
            f"reflec file {filename} does not have column {col + 1} "
            f"for {grazing_angle_deg} deg data."
        )

    energy = data[:, 0]
    efficiency = data[:, col]
    return energy, efficiency


def main():
    """Main function to process and plot simulation data."""
    print("SLAG Simulation Data Plotter")
    
    simulation_file = 'SLAG_simulation_400lmm_alpha4.0deg_order1_sub_Si_layer_Pt_20260423_160515.csv'
    experimental_file = 'Re__ELISA,_400l_mm_laminar_grating_from_HORIBA/lG400-HZB-ELISA_ascan-energy_alpha-4deg_1-order.csv'
    reflec_diff_file = "Reflec_simulations/Simulations_REFLEC_DiffMOD.txt"
    reflec_specs_file = "Reflec_simulations/Simulations_REFLEC_REFLEC(SPECS).txt"
    reflec_cont_file = "Reflec_simulations/Simulations_REFLEC_REFLEC(SPECS-cont).txt"
    reflec_afm_file = "Reflec_simulations/Simulations_REFLEC_REFLEC(AFM).txt"
    reflec_grazing_angle_deg = 4  # change to 2 to use the 2 deg reflec curve
  
    # Check command line arguments (optional override)
    if len(sys.argv) >= 2:
        simulation_file = sys.argv[1]
    if len(sys.argv) >= 3:
        experimental_file = sys.argv[2]
    if len(sys.argv) >= 4:
        reflec_diff_file = sys.argv[3]
    if len(sys.argv) >= 5:
        reflec_grazing_angle_deg = int(float(sys.argv[4]))
    
    # Validate simulation file
    if not os.path.exists(simulation_file):
        print(f"Error: Simulation file '{simulation_file}' not found.")
        print("Please edit the script and set the correct file paths, or use command line arguments.")
        sys.exit(1)
    # Check for experimental data file
    experimental_energy = None
    experimental_efficiency = None
    reflec_diff_energy = None
    reflec_diff_efficiency = None
    reflec_specs_energy = None
    reflec_specs_efficiency = None
    reflec_cont_energy = None
    reflec_cont_efficiency = None
    reflec_afm_energy = None
    reflec_afm_efficiency = None
    if experimental_file and os.path.exists(experimental_file):
        print(f"Found experimental file: {experimental_file}")
    else:
        experimental_file = None
        print("No experimental file provided or file not found.")

    if reflec_diff_file and os.path.exists(reflec_diff_file):
        print(f"Found reflec file: {reflec_diff_file}")
    else:
        reflec_diff_file = None
        print("No reflec file provided or file not found.")
    
    print(f"\nProcessing: {simulation_file}")
    
    # Parse the simulation CSV file
    try:
        metadata, energy, efficiency = parse_csv_with_metadata(simulation_file)
    except Exception as e:
        print(f"Error reading simulation file: {e}")
        sys.exit(1)
    
    # Parse experimental data if provided
    if experimental_file:
        try:
            experimental_energy, experimental_efficiency = parse_experimental_csv(experimental_file)
            print(f"Loaded {len(experimental_energy)} experimental data points")
        except Exception as e:
            print(f"Error reading experimental file: {e}")
            sys.exit(1)

    if reflec_diff_file:
        try:
            reflec_diff_energy, reflec_diff_efficiency = parse_reflec_simulations(
                reflec_diff_file, reflec_grazing_angle_deg
            )
            print(
                f"Loaded {len(reflec_diff_energy)} reflec data points "
                f"for {reflec_grazing_angle_deg} deg"
            )
        except Exception as e:
            print(f"Error reading reflec file: {e}")
            sys.exit(1)

    if reflec_specs_file:
        try:
            reflec_specs_energy, reflec_specs_efficiency = parse_reflec_simulations(
                reflec_specs_file, reflec_grazing_angle_deg
            )
            print(
                f"Loaded {len(reflec_specs_energy)} reflec data points "
                f"for {reflec_grazing_angle_deg} deg"
            )
        except Exception as e:
            print(f"Error reading reflec file: {e}")
            sys.exit(1)

    if reflec_cont_file:
        try:
            reflec_cont_energy, reflec_cont_efficiency = parse_reflec_simulations(
                reflec_cont_file, reflec_grazing_angle_deg
            )
            print(
                f"Loaded {len(reflec_cont_energy)} reflec data points "
                f"for {reflec_grazing_angle_deg} deg"
            )
        except Exception as e:
            print(f"Error reading reflec file: {e}")
            sys.exit(1)

    if reflec_afm_file:
        try:
            reflec_afm_energy, reflec_afm_efficiency = parse_reflec_simulations(
                reflec_afm_file, reflec_grazing_angle_deg
            )
            print(
                f"Loaded {len(reflec_afm_energy)} reflec data points "
                f"for {reflec_grazing_angle_deg} deg"
            )
        except Exception as e:
            print(f"Error reading reflec file: {e}")
            sys.exit(1)
    
    # Print metadata
    print_metadata(metadata)
    
    # Check if we have data
    if len(energy) == 0 or len(efficiency) == 0:
        print("Error: No data found in file.")
        sys.exit(1)
    
    # Create plot
    output_file = plot_data(metadata, energy, efficiency, 
                           experimental_energy, experimental_efficiency,
                           reflec_diff_energy, reflec_diff_efficiency,
                           reflec_specs_energy, reflec_specs_efficiency,
                           reflec_cont_energy, reflec_cont_efficiency,
                           reflec_afm_energy, reflec_afm_efficiency,
                           reflec_grazing_angle_deg,
                           show_plot=False)
    
    print(f"\nDone! Output file: {output_file}")


if __name__ == '__main__':
    main()
